#!/usr/bin/env php
<?php
require __DIR__ . '/../../autoload.php';

use Symfony\Component\Console\Application;
use Rumble\Command\MigrateCommand;
use Rumble\Command\SeedCommand;

$app = new Application('Rumble: DynamoDb migration tool.');
$app->add(new MigrateCommand());
$app->add(new SeedCommand());
$app->run();
